version: '3'
services:

  petclinic-db.default.svc.cluster.local:
    build:
      context: ..
      dockerfile: docker/Dockerfile.db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=demo
      - MYSQL_DATABASE=petclinic
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"

  petclinic:
    depends_on:
    - petclinic-db.default.svc.cluster.local
    build:
      context: ..
      dockerfile: docker/Dockerfile.app
#    ports:
#      - "8080:8080"
#      - "8000:8000"
