on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: petclinicproject.azurecr.io
        username: ${{ secrets.acr_petclinicproject_username }}
        password: ${{ secrets.acr_petclinicproject_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t petclinicproject.azurecr.io/petclinickubcluster:${{ github.sha }}
        docker push petclinicproject.azurecr.io/petclinickubcluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_petclinickubcluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep petclinickubcluster5d04 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace petclinickubcluster5d04`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: petclinickubcluster5d04
        container-registry-url: petclinicproject.azurecr.io
        container-registry-username: ${{ secrets.acr_petclinicproject_username }}
        container-registry-password: ${{ secrets.acr_petclinicproject_password }}
        secret-name: petclinickubdockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: petclinickubcluster5d04
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          petclinicproject.azurecr.io/petclinickubcluster:${{ github.sha }}
        imagepullsecrets: |
          petclinickubdockerauth